name: Build and Deploy APK

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7  # Adjust to your project's Python version

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386

    - name: Install Buildozer
      run: pip install buildozer

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-apk
        path: bin/  # Adjust this path if needed

